To Do list: interactive list
ZuhRa-HashiMi/To_Do_list_interactive- pull request #1
Opened 2022-11-11 17:48 UTC by ZuhRa-HashiMi

Use webpack to bundle JavaScript.
Learn how to use proper ES6 syntax.
Use ES6 modules to write modular JavaScript.

2022-11-11 18:17 UTC, christianbiring1 requested changes
Hi @ZuhRa-HashiMi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/201403138-96f31c11-be92-49db-b05a-19bceb58f2fc.gif)


## Highlights
- [ ] All linters checks are passing :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`
- [ ] Good commit message


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 18:17 UTC, christianbiring1 commented on src/index.js
> +      }
- [ ] Also you may consider the remove the completed tasks when the user clicks on `clear all completed`. 

`Hint: You may consider grabbing this removeItem fx in an click event`

- [ ] Also, for a better UX you may consider fixing the path of your image.
![image](https://user-images.githubusercontent.com/97100091/201402597-48e2fbc6-da3e-45dc-b8f2-e61741824f7f.png)

2022-11-11 18:17 UTC, christianbiring1 commented on README.md
> +### Prerequisites
- [ ] Kinldy make sure you provide descriptive and easy-to-understand instructions on how to run the project locally.

`hint: You may say: To clone the repos run in the terminal git clone <REPO_LINK>`
`To navigate over it : cd <DIRECTORY_NAME>`
`You may also consider not forgetting about the dependencies insatllation` :smile: 
`...`

2022-11-12 14:35 UTC, levy002 requested changes
## Hello @ZuhRa-HashiMi   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] As requested by the previous reviewer, kindly make sure when we click on the `Clear all completed` button every checked task is deleted. :wink: 

   - ### YOUR WEBSITE NOW
    ![chrome-capture-2022-10-12 (4)](https://user-images.githubusercontent.com/87197412/201479059-b4dd4f20-e3d1-49cb-9e85-3c3d0e627b88.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly make sure the task `index` must always start at `1` not from `0`.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 18:16 UTC, ElsonOtake approved these changes
# status: APPROVED :green_circle: :100: 

Hi @ZuhRa-HashiMi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 

![Minions](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. 👍 👍 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 18:16 UTC, ElsonOtake commented on README.md
> +- npm start.**
- [OPTIONAL] I think it's better to fix this command to correct instructions about how to run your project. Your project will look more professional and create a better UX.

<img width="546" alt="Screen Shot 2022-11-12 at 3 13 52 PM" src="https://user-images.githubusercontent.com/47673311/201488769-48d79801-e962-4454-9fb5-150f717213d0.png">

2022-11-12 18:36 UTC, merged